### ISSUE TITLE
export 'Errors' (imported as 'Errors') was not found in 'datastore-core'

### ISSUE THREAD

**Issue by osilkin98** [ipfs/js-datastore-level#122]
Hi,

I'm running into a problem where I'm attempting to instantiate an IPFS node within a simple TypeScript React app, and I'm given a `export 'Errors' (imported as 'Errors') was not found in 'datastore-core'` error after running `yarn start`:

```console
ERROR in ./node_modules/datastore-level/esm/src/index.js 45:12-36
export 'Errors' (imported as 'Errors') was not found in 'datastore-core' (possible exports: BaseDatastore, KeyTransformDatastore, MemoryDatastore, MountDatastore, NamespaceDatastore, NextToLast, PREFIX, Prefix, README_FN, SHARDING_FN, ShardBase, ShardingDatastore, Suffix, TieredDatastore, abortedError, dbDeleteFailedError, dbOpenFailedError, dbWriteFailedError, notFoundError, parseShardFun, readShardFun, readme)
```

The import statement itself is in `datastore-level/esm/src/index.js`:
```js
// imports
import {
  BaseDatastore,
  Errors
} from 'datastore-core';
```

`datastore-core` itself seems to export `Errors` within `datastore-core/types/src/index.d.ts`:
```js
export { BaseDatastore } from "./base.js";
export { MemoryDatastore } from "./memory.js";
export { KeyTransformDatastore } from "./keytransform.js";
export { ShardingDatastore } from "./sharding.js";
export { MountDatastore } from "./mount.js";
export { TieredDatastore } from "./tiered.js";
export { NamespaceDatastore } from "./namespace.js";
export * as Errors from "./errors.js";
export * as shard from "./shard.js";
export type Shard = import("./types").Shard;
export type KeyTransform = import("./types").KeyTransform;
//# sourceMappingURL=index.d.ts.map
```

It looks like the specific datastore-core version that I'm using is `7.0.2`:
```
datastore-core@^7.0.0:
  version "7.0.2"
  resolved "https://registry.yarnpkg.com/datastore-core/-/datastore-core-7.0.2.tgz#014f4d04e9a5b397b15ec1cfe4a99965e2342a18"
  integrity sha512-IDu4fVbXY6kjGV8Iys6vsw43dm1jDd+d4vfFmrgXycEKpHtMSAeELUQWgrN/Li9U9w2TSVG96RbvE2Yax2LTUQ==
```

**Comment by osilkin98** [comment]
Things I've tried:
- removing ipfs-types / ipfs-core-types
- upgrading datastore-level with `yarn upgrade datastore-level datastore-core`
- adding them as the latest dependencies with `yarn add --dev datastore-level@latest datastore-core@latest`

**Comment by achingbrain** [comment]
The code above is from an older version which was dual published as ESM and CJS, the tooling around this can sometimes cause problems.

Could you please try again with the latest version, it's ESM-only so should hopefully not have this problem any more.
