### ISSUE TITLE
More detailed usage

### ISSUE THREAD

**Issue by yuhr** [ipfs/js-datastore-level#59]
The section "Usage" in the readme is not fully illustrating how to use this module with `ipfs-core`. Could you provide more information? How can I pass this module to "IPFS.create" API?

I'm struggling to make IPFS work entirely in memory. My current setup is following (constructed according to https://github.com/ipfs/js-ipfs/blob/master/examples/custom-ipfs-repo/index.js), but it emits `OpenError: IO error: .ipfs/kptQGJNdBNgFcQxtixKUw/pins/LOCK: No such file or directory`.

```typescript
import IPFS from "ipfs-core"
import { nanoid } from "nanoid"
import Repo from "ipfs-repo"
import DatastoreLevel from "datastore-level"
import LevelMem from "level-mem"
import LockMemory from "ipfs-repo/src/lock-memory"

const ipfs = await IPFS.create({
  repo: new Repo(`.ipfs/${nanoid()}`, {
    storageBackends: {
      root: DatastoreLevel,
      blocks: DatastoreLevel,
      keys: DatastoreLevel,
      datastore: DatastoreLevel
    },
    storageBackendOptions: {
      root: { db: LevelMem },
      blocks: { db: LevelMem },
      keys: { db: LevelMem },
      datastore: { db: LevelMem }
    },
    lock: LockMemory
  }),
  start: false,
  silent: true,
  init: {
    algorithm: "Ed25519"
  }
})
```

**Comment by aschmahmann** [comment]
This looks like a general support request. Try asking on https://discuss.ipfs.io as it'll be more visible to the community (nobody looks at closed GitHub issues).

**Comment by achingbrain** [comment]
@yuhr if you want to run everything in memory, use `MemoryDataStore` from `interface-datastore` instead of `datastore-level` - https://github.com/ipfs/interface-datastore


```js
const MemoryStore = require('interface-datastore').MemoryDatastore
```

```js
const ipfs = await IPFS.create({
  repo: new Repo(`.ipfs/${nanoid()}`, {
    storageBackends: {
      root: MemoryStore,
      // etc
```

**Comment by yuhr** [comment]
@aschmahmann Okay sorry, but I think this is rather an issue that the docs is lacking adequate information, though this could apply not only to this repo. I definitely think in-memory use case is pretty common, but the answer @achingbrain provided is not reachable from the readme of https://github.com/ipfs/js-ipfs.

Though, let's move to https://discuss.ipfs.io, if you say nobody looks here. Thanks @achingbrain, but the general-support-request-like part of my question is still not resolved. Written here: https://discuss.ipfs.io/t/datastore-setup/10385
