### ISSUE TITLE
Master branch currently doesn't pass tests on 10.0.0

### ISSUE THREAD

**Issue by victorb** [ipfs/js-datastore-level#9]
See the test failures at: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-datastore-level/detail/master/5/tests

Seems to be mostly the same failures across tests, namely a `WriteError: QuotaExceededError` error gets thrown.

**Comment by achingbrain** [comment]
This issue hasn't occurred since we moved to Travis.  Will reopen if it happens again.
